### ISSUE TITLE
Make add comment mark a task complete

### ISSUE THREAD

**Issue by TheNathanBlack** [dertuxmalwieder/SublimeTodoTxt#10]
Would be nice to have a key combo automatically mark a line finished. Maybe override "Add comment" functionality?

**Comment by dertuxmalwieder** [comment]
I'm not a fan of overriding defaults depending on the file without any user interaction. As a user, I'd prefer to leave my defaults untouched.

But I'm open for suggestions. :-)

**Comment by TheNathanBlack** [comment]
But when we are in the Todo.txt context, setting something as a comment
doesn't have a meaning.

**Comment by dertuxmalwieder** [comment]
But your *muscle memory* will be confused.

I randomly use Emacs for Todo.txt files on some platforms and it has *entirely different* key combinations for using them than it has for normal text files - for this very reason.
