### ISSUE TITLE
Create a page for the todo

### ISSUE THREAD

**Issue by mhalano** [dertuxmalwieder/SublimeTodoTxt#15]
This guy aziz (https://github.com/aziz/PlainTasks) create a plugin for SublimeText to manage ToDos. I know the format of the file is different, but instead just highlight could be a screen working as GUI with boxes and check marks.

**Comment by dertuxmalwieder** [comment]
Technically, yes, but that would probably pervert the point behind having a plain text TODO.

**Comment by mhalano** [comment]
That's a valid point, but if you think this way even todo.txt CLI program is a perversion. The idea, I think, is if you want, you could read and edit the file in a simple text editor. The idea is create a interface using todo.txt format as backend so you can use shortcuts and so on to manage easily the file.

**Comment by dertuxmalwieder** [comment]
Which is not what a text editor is for, right? I mean, if you want to have a GUI, you'll probably avoid Todo.txt/org-mode/etc.

**Comment by mhalano** [comment]
I don't think so. Backend isn't the same as GUI. I like todo.txt because
the simple and portable format. I use GUIs to manipulate the todo.txt file
(DayTasks on Linux and SimpleTasks on Android). The idea is create a GUI to
make easy manipulate todo.txt using shortcuts and etc. on Sublime Text
style in a integrated way. Org-mode is a interface to plan events, create
notes, etc. but do the things on Emacs style.

Did you understand my point?

Em qui, 16 de jun de 2016 às 11:51, Cthulhux <notifications@github.com>
escreveu:

> Which is not what a text editor is for, right? I mean, if you want to have
> a GUI, you'll probably avoid Todo.txt/org-mode/etc.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dertuxmalwieder/SublimeTodoTxt/issues/15#issuecomment-226509024>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFvvR_pqjGV_NhD6ocJoRDaXd3eSsSerks5qMWLzgaJpZM4I25oE>
> .
>
-- 

Sent from my Android

**Comment by dertuxmalwieder** [comment]
Yes, but I actually like the Emacs approach of having text formatted as text... :-)
