### ISSUE TITLE
Remove the dot `.` on the package name `Todo.txt Syntax`

### ISSUE THREAD

**Issue by evandrocoan** [dertuxmalwieder/SublimeTodoTxt#23]
On https://github.com/wbond/package_control_channel/pull/2524 (Test against package names containing periods) was determinate that Sublime Text 3 cannot support package names within dot on their names. Then all the packages with dot `.` on their names should either be renamed without the dot, or marked as `Sublime Text 2` supported.

If after sometime, a pull request to `package_control_channel` removing the dot `.` on the package name is not sent, the package will be marked as supported by `Sublime Text 2` only. Currently the package is marked as supported by all versions of Sublime Text.

**Comment by dertuxmalwieder** [comment]
Does Package Control support updating a package which changes its name?

**Comment by evandrocoan** [comment]
Sure. You just need to set the `previous_names` setting, and everybody who has installed your package will get their installed name renamed as soon as package control starts updating the packages. Example:
```json
		{
			"name": "FoldFunctions",
			"previous_names": ["Fold Functions"],
			"details": "https://github.com/math2001/FoldFunctions",
			"releases": [
				{
					"sublime_text": ">=3126",
					"tags": true
				}
			]
		},
```

**Comment by dertuxmalwieder** [comment]
As far as I can see, the limitation does *not really* affect SublimeTodoTxt as I don't have any Python code here. But for convenience, I'll submit a change request...

Thank you for telling me. :)
