### ISSUE TITLE
Allow whitespace in front of 'x'?

### ISSUE THREAD

**Issue by ryanpcmcquen** [dertuxmalwieder/SublimeTodoTxt#27]
I have a `TODO.txt` file, with some subtasks, for example:

```
) Foo
    x ) Bar
    ) Baz
```

I'd like the _Bar_ entry to syntax highlight, wondering if this is feasible or practical ...

**Comment by dertuxmalwieder** [comment]
> to syntax highlight

As in, "done"? Well, it probably is. Here's my (blind) attempt: Replace line 25 in the syntax file:

    - match: ^x\s.*$

by:

    - match: ^\s*x\s.*$

**Comment by ryanpcmcquen** [comment]
@dertuxmalwieder, that should do it!

**Comment by dertuxmalwieder** [comment]
Good! Send me a PR if you want to have it in here permanently.

**Comment by ryanpcmcquen** [comment]
@dertuxmalwieder: https://github.com/dertuxmalwieder/SublimeTodoTxt/pull/28
