### ISSUE TITLE
Autosave todo.txt files in sublime

### ISSUE THREAD

**Issue by 40-02** [dertuxmalwieder/SublimeTodoTxt#3]
Hi there:)

It is not an issue, but feature request 

You might know how to create a syntax specific setting to automaticaly save todo.txt file. 

I've found that this is possible here:
http://stackoverflow.com/questions/20810239/sublime-text-autosave-only-for-specific-files

**Comment by MichaelTunnell** [comment]
@sheabunge thank you for that...that is super useful!
