### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by tristan-k** [dertuxmalwieder/SublimeTodoTxt#9]
Please provide instructions on how to install SublimeTodoTxt.

**Comment by dertuxmalwieder** [comment]
Grab it from Package Control or put the file(s) into your Packages directory and reload Sublime Text. Then open a Todo.txt file.

**Comment by tristan-k** [comment]
It's not available in Package Control. I did a search for SublimeTodoTxt.

**Comment by dertuxmalwieder** [comment]
[Here it is](https://packagecontrol.io/packages/Todo.txt%20Syntax).

I'll update the README, sorry.

**Comment by tristan-k** [comment]
It's strange. I cant locate it through Package Control inside Sublime Text 3.

**Comment by dertuxmalwieder** [comment]
Maybe ask @wbond then? I don't have Sublime Text on this machine, so I can't really check it myself until the evening, sorry. :/

**Comment by MichaelTunnell** [comment]
It is located in Package Control, that is how I installed it.

@tristan-k here is how it is done:

1. Ctrl+Shift+P to launch the Command Palette.
2. Type in "packin" this will select "Package Control: Install Package", press Enter.
3. Type in "todo", select "Todo.txt Syntax" and press Enter.
4. You will need to close and restart Sublime Text to get the syntax activated.
